server:
  port: 8082

spring:
  application:
    name: mailbox-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mailvault}
    username: ${DB_USERNAME:mailvault}
    password: ${DB_PASSWORD:mailvault}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
